name: PlantBaby
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0

targets:
  PlantBaby:
    type: application
    platform: iOS
    sources:
      - PlantBaby
    settings:
      base:
        INFOPLIST_FILE: PlantBaby/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.plantbaby
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: PlantBaby/Info.plist
      properties:
        CFBundleDisplayName: PlantBaby
        CFBundleIdentifier: com.yourcompany.plantbaby
        CFBundleName: PlantBaby
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes: []
